apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: rdicidr
  name: rdicidr
  namespace: production
spec:
  ports:
  - name: 8080-3000
    port: 8080
    protocol: TCP
    targetPort: 3000
  selector:
    app: rdicidr
  type: ClusterIP
status:
  loadBalancer: {}
